### ISSUE TITLE
Rename Page Title

### ISSUE THREAD

**Issue by FreshDave29** [cleptric/super-potato#8]
Currently the page is titled "Home" which makes it difficult to find, if you have multiple browser sessions. 
Please rename the page to something more meaningful.

**Comment by cleptric** [comment]
@FreshDave29 Would you like to see something like "🥔  LOWW" in the title if you select LOWW in the menu?

**Comment by FreshDave29** [comment]
Yes, or at least a "LOWW - SuperPotato" if text only is required

**Comment by cleptric** [comment]
This will be part of version 2.0.0 👍

![Screenshot 2021-12-04 at 08 33 02](https://user-images.githubusercontent.com/6617432/144701684-ba241735-c1d0-4689-987e-f9f8a97cd9f1.png)
